version: '3.7'

services:
  flask:
    build:
      context: ./flask
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      FLASK_RUN_PORT: 80
      FLASK_RUN_HOST: 0.0.0.0
    stop_signal: SIGINT
    volumes:
      - ./flask:/app
    networks:
      - app-network
    
  # Fck dis :-)
  # db:
  #   image: postgres:12
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: database
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - db-data:/var/lib/postgresql/data
  #     - ./schema.sql:/docker-entrypoint-initdb.d/init.sql
  #   networks:
  #     - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge

